name: Validate Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source and target
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const sourceBranch = pr.head.ref;
            const targetBranch = pr.base.ref;
            const title = pr.title.toLowerCase();

            // Condición 1: No permitir PRs a main/master si no vienen de dev
            if ((targetBranch === 'main' || targetBranch === 'master') && sourceBranch !== 'dev') {
              if (!title.includes('hotfix')) {
                core.setFailed(`Solo se permiten PRs a ${targetBranch} desde la rama 'dev', excepto si el título contiene 'hotfix'.`);
              }
            }

    
